services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: doc-schedule
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: doc-schedule
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
